version: '3.8'

services:
  app:
    image: evershop/evershop:latest
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
    networks:
      - myevershop
    depends_on:
      - database
    ports:
      - 3000:3000
  
  #The postgres database: 
  database:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - myevershop

  # MCP PostgreSQL Server
  mcp-postgres:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    restart: unless-stopped
    environment:
      POSTGRES_CONNECTION_STRING: "postgresql://postgres:postgres@database:5432/postgres"
    networks:
      - myevershop
    depends_on:
      - database
    ports:
      - "8001:8001"

  # streamlit-customer-agent:

  # streamlit-customer-csm:

  # # fastapi-server:

networks:
  myevershop:
    name: MyEverShop
    driver: bridge

volumes:
  postgres-data:
